config/routes.rb
Rails.application.routes.draw do

  get 'main', to: 'users#show'

  get 'mains/question'
  get 'mains/maintenance'
  get 'mains/rank'

  get 'question_similer_words/new'

  get 'questions/index'
  post 'question/index', to: 'questions#judge'
  get 'questions/new'
  get 'questions/maintenance'
  get 'questions/judge'

  get 'maintenances/new'
  get 'maintenances/search'
  get 'maintenances/edit'
  get 'maintenances/delete'

  match '/maintenances_create' => 'maintenances#create', via: [ :post ]

  root to: 'users#index'

  get 'sessions/new'

  # get 'users/index'

  # get 'users/new'

  # get 'users/create'

  # get 'users/edit'

  # get 'users/show'

  # get 'users/update'

  # get 'users/destroy'
  resources :users 

  # ログイン / ログアウト
  get     'login',   to: 'sessions#new'
  post    'login',   to: 'sessions#create'
  delete  'logout',  to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/question_similer_word.rb
class QuestionSimilerWord < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password validations: true

	validates :mail, presence: true, uniqueness: true


	def self.new_remember_token
      SecureRandom.urlsafe_base64
    end

    def self.encrypt(token)
      Digest::SHA256.hexdigest(token.to_s)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :current_user
  before_action :require_sign_in!
  helper_method :signed_in?

  protect_from_forgery with: :exception

  def current_user
    remember_token = User.encrypt(cookies[:user_remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:user_remember_token] = remember_token
    user.update!(remember_token: User.encrypt(remember_token))
    @current_user = user
  end

  def sign_out
    @current_user = nil
    cookies.delete(:user_remember_token)
  end

  def signed_in?
    @current_user.present?
  end

  private

    def require_sign_in!
      redirect_to login_path unless signed_in?
    end

end

app/controllers/maintenances_controller.rb
class MaintenancesController < ApplicationController
  def new
  	@question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to '/questions/maintenance'
    else
      render 'no'
    end
  end

  def search
  end

  def edit
  end

  def delete
  end

  private

    def question_params
      params.require(:question).permit(:question, :description)
    end

end

app/controllers/question_similer_words_controller.rb
class QuestionSimilerWordsController < ApplicationController
  def new
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  
  def new
  end

  def index
    @question = Question.all.sample(4)
    @answer = @question.sample
    @@answer = @answer
  end

  def judge
    @answer = @@answer
    @select = Question.find(params["question_id"])
    if @answer == @select
      @result = "正解"
    else
      @result = "不正解"      
    end
  end

  def maintenance
  end
 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :require_sign_in!, only: [:new, :create]
  before_action :set_user, only: [:create]

  def new
  end

  def create
    if @user.authenticate(session_params[:password])
      sign_in(@user)
      redirect_path = users_show_path @user
      redirect_to redirect_path
    else
      flash.now[:danger] = t('.flash.invalid_password')
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to login_path
  end

  def current_user
    remember_token = User.encrypt(cookies[:user_remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end  

  def logged_in?
    !current_user.nil?
  end
  
  private

    def set_user
      @user = User.find_by!(mail: session_params[:mail])
    rescue
      flash.now[:danger] = t('.flash.invalid_mail')
      render action: 'new'
    end

    # 許可するパラメータ
    def session_params
      params.require(:session).permit(:mail, :password)
    end
    
    def users_show_path user
      users_path + "/" + "#{user.id}"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_sign_in!, only: [:new, :create]

  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path
    else
      render 'new'
    end
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end


  def login_form
  end

  def login
    @user = User.find_by(name: params[:name], password: params[:password])

    if @user
      flash[:notice] = "ログインしました"
      redirect_to("/users/index")
    else
      render("users/login_form")
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :mail, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/maintenances_helper.rb
module MaintenancesHelper
end

app/helpers/question_similer_words_helper.rb
module QuestionSimilerWordsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WordApp2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/maintenances/delete.html.erb
<h1>Maintenances#delete</h1>
<p>Find me in app/views/maintenances/delete.html.erb</p>

app/views/maintenances/edit.html.erb
<h1>Maintenances#edit</h1>
<p>Find me in app/views/maintenances/edit.html.erb</p>

app/views/maintenances/new.html.erb
<h1>Maintenances#new</h1>

<%= form_for @question, url: maintenances_create_path do |f|%>

  <%= f.label :question%>
  <%= f.text_field :question%>

  <%= f.label :description%>
  <%= f.text_field :description%>

  <%= f.submit '登録'%>
 <% end %>

app/views/maintenances/search.html.erb
<h1>Maintenances#search</h1>
<p>Find me in app/views/maintenances/search.html.erb</p>

app/views/question_similer_words/new.html.erb
<h1>QuestionSimilerWords#new</h1>
<p>Find me in app/views/question_similer_words/new.html.erb</p>

app/views/questions/index.html.erb
<h1>単語帳</h1>

<!-- 
<br>
<br>
<%= form_for :params, url: 'judge' do |f| %>
<%= select_tag :question_id, options_from_collection_for_select(@question, :id, :description) %>
<%= f.submit "送信" %>
<% end %>
<br>
<br>
<br>
 -->

<%= form_tag({controller: :questions, action: :judge}) do %>
	<p>
		問題：
		<%= @answer.question %>
	</p>
	<p>
		<%= select_tag :question_id, options_from_collection_for_select(@question, :id, :description) %>
		<%= submit_tag "送信"%>
	</p>
<% end %>

<br>
<br>
<%= link_to 'メインメニュー', '/users/show' %>

app/views/questions/judge.html.erb
<h1>
	judge
</h1>
<br>
<h2>
	<%= @result %>
</h2>
<p>
	問題：<%= @answer.question %>
</p>
<p>
	答え：<%= @answer.description %>
</p>
<p>
	選択した答え：<%= @select.description %>
</p>

app/views/questions/maintenance.html.erb
Questions#maintenance<br>

<%= link_to '新規登録', '/maintenances/new' %><br>
<%= link_to '検索', '/maintenances/search' %><br>
<%= link_to '修正', '/maintenances/edit' %><br>
<%= link_to '削除', '/maintenances/delete' %>

app/views/questions/new.html.erb
<h1>Questions#new</h1>
<p>Find me in app/views/questions/new.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Main Manu</h1>

app/views/users/login_form.html.erb
<h1>ログイン</h1>

<%= form_tag("/login") do %>
 <p>名前</p>
  <!-- name属性を追加してください -->
  <input name ="name">
  <p>パスワード</p>
  <!-- name属性を追加してください -->
  <input type="password" name ="password">
  <input type="submit" value="ログイン">
  <!-- form_tag用のendを追加してください -->
 <% end %>

app/views/users/new.html.erb
<h1>ユーザー登録</h1>

<%= form_for @user, url: users_path do |f|%>

  <%= f.label :name%>
  <%= f.text_field :name%>

  <%= f.label :mail%>
  <%= f.text_field :mail%>

  <%= f.label :password%>
  <%= f.text_field :password%>

  <%= f.label :password_confirmation%>
  <%= f.text_field :password_confirmation%>

  <%= f.submit '登録'%>
 <% end %>

app/views/users/show.html.erb
<h1>Main Manu</h1>

<%= link_to '新規ユーザ作成', '/users/new' %><br>
<%= link_to '単語帳', '/questions/index' %><br>
<%= link_to '単語マスタメンテナンス', '/questions/maintenance' %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>